### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by li980432131** [xingyizhou/CenterNet#184]
ubuntu18  Cuda 9.2  torch==0.4.1 2080ti
when i run demo.py , i meet "cuda out of memory"
who can help me?@.@

(centernet1) li@li:~/PycharmProjects/CenterNet-master(1)/CenterNet-master/src$ python demo.py ctdet --demo /home/li/Documents/baozong.avi --load_model ../models/ctdet_coco_dla_2x.pth
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/li/PycharmProjects/CenterNet-master(1)/CenterNet-master/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "demo.py", line 57, in <module>
    demo(opt)
  File "demo.py", line 31, in demo
    ret = detector.run(img)
  File "/home/li/PycharmProjects/CenterNet-master(1)/CenterNet-master/src/lib/detectors/base_detector.py", line 116, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "/home/li/PycharmProjects/CenterNet-master(1)/CenterNet-master/src/lib/detectors/ctdet.py", line 26, in process
    output = self.model(images)[-1]
  File "/home/li/.conda/envs/centernet1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/PycharmProjects/CenterNet-master(1)/CenterNet-master/src/lib/models/networks/pose_dla_dcn.py", line 481, in forward
    z[head] = self.__getattr__(head)(y[-1])
  File "/home/li/.conda/envs/centernet1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/.conda/envs/centernet1/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/li/.conda/envs/centernet1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/.conda/envs/centernet1/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by li980432131** [comment]
I have solved it by setting "torch.backends.cudnn.enabled = False".

**Comment by xingyizhou** [comment]
Thanks for the solution!

**Comment by 201814476285951** [comment]
Could you tell me it is where?

**Comment by violet17** [comment]
> Could you tell me it is where?

@201814476285951   you can add it in demo.py.

**Comment by 201814476285951** [comment]
@violet17  thanks a lot.

**Comment by lxfhfut** [comment]
torch.backends.cudnn.deterministic = True
