### ISSUE TITLE
run demo error

### ISSUE THREAD

**Issue by popruckyowl** [xingyizhou/CenterNet#70]
CenterNet work on ubuntu16.04+pytorch0.4.1+python3.5+cuda9.0

When I set the --demo '/home/didi/data/247.png'  --load_model '/home/didi/Documents/CenterNet-master/models/ctdet_coco_dla_2x.pth', and run the demo.py on ctdet mode.

I got the following error:

Fix size testing.
training chunk_sizes: [8]
The output will be saved to  /home/didi/Documents/CenterNet-master/src/lib/../../exp/ctdet/default
heads {'wh': 2, 'reg': 2, 'hm': 80}
Creating model...
loaded /home/didi/Documents/CenterNet-master/models/ctdet_coco_dla_2x.pth, epoch 230
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=2 : out of memory
Traceback (most recent call last):
  File "/home/didi/software/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/didi/software/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/didi/software/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/didi/software/pycharm-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/didi/Documents/CenterNet-master/src/demo.py", line 59, in <module>
    demo(opt)
  File "/home/didi/Documents/CenterNet-master/src/demo.py", line 50, in demo
    ret = detector.run(image_name)
  File "/home/didi/Documents/CenterNet-master/src/lib/detectors/base_detector.py", line 116, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "/home/didi/Documents/CenterNet-master/src/lib/detectors/ctdet.py", line 26, in process
    output = self.model(images)[-1]
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/didi/Documents/CenterNet-master/src/lib/models/networks/pose_dla_dcn.py", line 481, in forward
    z[head] = self.__getattr__(head)(y[-1])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

Then I used pycharm to check where the error occurred, I found it stop at 26 of ctdet.py.
The model loaded correctly, however, no matter what size of 247.png I gave, it just couldn't pass.

How can I solve this problem?

**Comment by nanditam1** [comment]
Hi, Even I have encountered this error of CUDA out of memory. Any idea on the cause of this error? I am working with Ubuntu18.04, 2080 RTX Ti, cuda-9.0, pytorch 0.4.1, python3.5

**Comment by xingyizhou** [comment]
DLA takes less than 2G GPU memory in my machine. Please check if your GPU is occupied by other programs.

**Comment by westpilgrim** [comment]
I encountered the same problem, my GPU memory is not occupied

**Comment by westpilgrim** [comment]
even I add the tag  --batch_size 1 ,still the same problem

**Comment by westpilgrim** [comment]
forget to mention that my gpu memory is 6g

**Comment by lvbubu** [comment]
I also encountered this error of CUDA out of memory，I am working with Ubuntu16.04, 2080 RTX Ti, cuda-9.0, pytorch 0.4.1, python3.6，my GPU memory is 8G.

**Comment by lvbubu** [comment]
> Hi, Even I have encountered this error of CUDA out of memory. Any idea on the cause of this error? I am working with Ubuntu18.04, 2080 RTX Ti, cuda-9.0, pytorch 0.4.1, python3.5. Thanks.

I encountered the same problem with Ubuntu16.04, 2080 RTX Ti, cuda-9.0, pytorch 0.4.1, python3.6 . Maybe it is because 2080 RTX Ti needs cuda10 and needs to install pytorch  by source code. I will not have this issue when I change a machine with Tesla v100, cuda-9.0, pytorch 0.4.1, python3.7.

**Comment by WangyiNTU** [comment]
My problem is the `os.environ['CUDA_VISIBLE_DEVICES'] = opt.gpus_str`. We need to set --gpus (default=0) to choose which GPU can be used. It works for me.

**Comment by nanditam1** [comment]
> > Hi, Even I have encountered this error of CUDA out of memory. Any idea on the cause of this error? I am working with Ubuntu18.04, 2080 RTX Ti, cuda-9.0, pytorch 0.4.1, python3.5. Thanks.
> 
> I encountered the same problem with Ubuntu16.04, 2080 RTX Ti, cuda-9.0, pytorch 0.4.1, python3.6 . Maybe it is because 2080 RTX Ti needs cuda10 and needs to install pytorch by source code. I will not have this issue when I change a machine with Tesla v100, cuda-9.0, pytorch 0.4.1, python3.7.

Hi, I am having trouble installing pytorch 0.4.1 from source in cuda-10.0. Keep getting this error : THCAtomics.cuh(100): error: cannot overload functions distinguished by return type alone. ubuntu version : 18.04. Any clues why this is happening?

**Comment by vivekpd15** [comment]
Having the same issue with RTX2070 and CUDA10. 

Any resolutions yet?

**Comment by westpilgrim** [comment]
> > > Hi, Even I have encountered this error of CUDA out of memory. Any idea on the cause of this error? I am working with Ubuntu18.04, 2080 RTX Ti, cuda-9.0, pytorch 0.4.1, python3.5. Thanks.
> > 
> > 
> > I encountered the same problem with Ubuntu16.04, 2080 RTX Ti, cuda-9.0, pytorch 0.4.1, python3.6 . Maybe it is because 2080 RTX Ti needs cuda10 and needs to install pytorch by source code. I will not have this issue when I change a machine with Tesla v100, cuda-9.0, pytorch 0.4.1, python3.7.
> 
> Hi, I am having trouble installing pytorch 0.4.1 from source in cuda-10.0. Keep getting this error : THCAtomics.cuh(100): error: cannot overload functions distinguished by return type alone. ubuntu version : 18.04. Any clues why this is happening?

hi have you solved the  out of memory problem?

**Comment by westpilgrim** [comment]
> CenterNet work on ubuntu16.04+pytorch0.4.1+python3.5+cuda9.0
> 
> When I set the --demo '/home/didi/data/247.png' --load_model '/home/didi/Documents/CenterNet-master/models/ctdet_coco_dla_2x.pth', and run the demo.py on ctdet mode.
> 
> I got the following error:
> 
> Fix size testing.
> training chunk_sizes: [8]
> The output will be saved to /home/didi/Documents/CenterNet-master/src/lib/../../exp/ctdet/default
> heads {'wh': 2, 'reg': 2, 'hm': 80}
> Creating model...
> loaded /home/didi/Documents/CenterNet-master/models/ctdet_coco_dla_2x.pth, epoch 230
> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=2 : out of memory
> Traceback (most recent call last):
> File "/home/didi/software/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1741, in 
> main()
> File "/home/didi/software/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1735, in main
> globals = debugger.run(setup['file'], None, None, is_module)
> File "/home/didi/software/pycharm-2019.1.1/helpers/pydev/pydevd.py", line 1135, in run
> pydev_imports.execfile(file, globals, locals) # execute the script
> File "/home/didi/software/pycharm-2019.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "/home/didi/Documents/CenterNet-master/src/demo.py", line 59, in 
> demo(opt)
> File "/home/didi/Documents/CenterNet-master/src/demo.py", line 50, in demo
> ret = detector.run(image_name)
> File "/home/didi/Documents/CenterNet-master/src/lib/detectors/base_detector.py", line 116, in run
> output, dets, forward_time = self.process(images, return_time=True)
> File "/home/didi/Documents/CenterNet-master/src/lib/detectors/ctdet.py", line 26, in process
> output = self.model(images)[-1]
> File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/didi/Documents/CenterNet-master/src/lib/models/networks/pose_dla_dcn.py", line 481, in forward
> z[head] = self.**getattr**(head)(y[-1])
> File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
> input = module(input)
> File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: CUDA error: out of memory
> 
> Then I used pycharm to check where the error occurred, I found it stop at 26 of ctdet.py.
> The model loaded correctly, however, no matter what size of 247.png I gave, it just couldn't pass.
> 
> How can I solve this problem?

hi have you solved the out of memory problem?

**Comment by westpilgrim** [comment]
> Having the same issue with RTX2070 and CUDA10.
> 
> Any resolutions yet?

hi have you solved this?

**Comment by PRYUS** [comment]
Check if your GPU has enough memory allocated for the process to run. That's the main issue for CUDA out of memory errors.

**Comment by CompliceU** [comment]
i run it with 2080ti  cuda9 cudnn7.3.1 ,i have also meet the same issue with you,have you solve it? @westpilgrim @popruckyowl

**Comment by westpilgrim** [comment]
> i run it with 2080ti cuda9 cudnn7.3.1 ,i have also meet the same issue with you,have you solve it? @westpilgrim @popruckyowl

I solved it by increase the GPU memory form 6g to 8g

**Comment by aviciiiii** [comment]
I set the "torch. Backends. Cudnn. Enabled = False" solved the problem

**Comment by aviciiiii** [comment]
I set the "torch. backends. cudnn. enabled = False" solved the problem

**Comment by zlheos** [comment]
in opts.py line 339
i change 'default_resolution': [512,512]  to [640,640] or [480,480]
it can work for me 
but i don't know why?

**Comment by staurfan** [comment]
> in opts.py line 339
> i change 'default_resolution': [512,512] to [640,640] or [480,480]
> it can work for me
> but i don't know why?

I follow your way,it also work for me.still not figure out?

**Comment by ggsggs** [comment]
I was getting weird out of memory errors with my dataset during testing. Exploring the dataset I found some big images (something like 4000x6000) in the dataset that caused the error. I solved it by capping the biggest border of the image to something more manageable (like 1024) at test time and maintaining the same aspect ratio.

**Comment by staurfan** [comment]
I set default resolution as 512*512,all images with out of memory errors,set as 480*480 or 640*640,there is no memory errors






At 2019-08-21 08:40:23, "GGS" <notifications@github.com> wrote:


I was getting weird out of memory errors with my dataset during testing. Exploring the dataset I found some big images (something like 4000x6000) in the dataset that caused the error. I solved it by capping the biggest border of the image to something more manageable (like 1024) at test time and maintaining the same aspect ratio.

**Comment by So-LiYatao** [comment]
> I set default resolution as 512*512,all images with out of memory errors,set as 480*480 or 640*640,there is no memory errors At 2019-08-21 08:40:23, "GGS" <notifications@github.com> wrote: I was getting weird out of memory errors with my dataset during testing. Exploring the dataset I found some big images (something like 4000x6000) in the dataset that caused the error. I solved it by capping the biggest border of the image to something more manageable (like 1024) at test time and maintaining the same aspect ratio. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

I changed the resolution and solved this problem when I run the demo.py, but the same problem occurs when I run the main.py to train my dataset  , changing the resolution is useless. Do you know how to solve it?
